WisApp/Wisapp/Wisapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'))

]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

WisApp/app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.conf import settings


app_name = "app"

urlpatterns = [
    path('returnPage/', views.returnPage, name='returnPage'),
    path('crearCuenta', views.submitNewUser, name="createNewAccount"),
    path('modificarInfoPerfil<pk>', views.UserWithProfileUpdate.as_view(), name="UserWithProfileUpdate"),
    path('login/', views.login, name='userLogin'),
    path('inicio/', views.home, name='home'),
    path('estadisticas/', views.showStatistics, name='showStatistics'),
    path('inicio/Categoria-<categoryId>-<categoryName>/', views.filteredHome, name='filteredHome'),
    path('inicio/MisHistorias/', views.homeMyStories, name='homeMyStories'),
    path('inicio/MisHistorias/Favoritas', views.homeMyFavoriteStories, name='homeMyFavoriteStories'),
    path('inicio/HistoriasPorAutor/<pk>', views.storyFilterByAuthor, name='storyFilterByAuthor'),
    path('inicio/autoresSeguidos/', views.followedAuthors, name='followedAuthors'),
    path('inicio/search/', views.search, name='search'),
    path('categorias/', views.categories, name='categories'),
    path('eventos/', views.events, name='events'),
    path('ver/perfil/<userId>', views.profile, name='profile'),
    path('historia/<storyId>', views.story, name='story'),
    path('crearHistoria/', views.submitStory, name='createStory'),
    path('crearPeticion/', views.createPetition, name='createPetition'),
    path('modificarHistoria<pk>/', login_required(views.StoryUpdate.as_view()), name='storyUpdate'),
    path('eliminarHistoria<pk>/', views.StoryDelete.as_view(), name='storyDelete'),
    path('eliminarCuenta<pk>/', views.UserDelete.as_view(), name='userwithprofileDelete'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),

]

Wisapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'))

]

WisApp/app/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.forms import FileInput, CheckboxSelectMultiple
from django.forms.fields import DateField
from .models import Story, UserWithProfile, Comment, PetitionForAdmin
from django.contrib.auth.models import User


class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        image = forms.ImageField(required=False, widget=FileInput,label='Elegir imagen')
        fields = [
            'title', 'message', 'category','image'
        ]
        labels = {
            'title': 'Título',
            'message': 'Descripción',
            'category': 'Categoría/Evento',
            'image':'imagen'
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control mx-auto font32'}),
            'message': forms.Textarea(attrs={'class': 'storyMessageInput keepWhitespaceFormatting'}),
            'category': forms.Select(attrs={'class': 'categorySelect mx-auto'}),
        }

    def __init__(self, *args, **kwargs):
        super(StoryForm, self).__init__(*args, **kwargs)
        self.fields['message'].strip = False

class PetitionAdmin( forms.ModelForm ):
    class Meta:
        model = PetitionForAdmin
        message = forms.CharField( widget=forms.Textarea(attrs={'rows': 5, 'cols': 100}))
        fields = [
            'title', 'message',
        ]
        labels = {
            'title': 'Título',
            'message': 'Descripción',
        }
    def __init__(self, *args, **kwargs):
        super(PetitionAdmin, self).__init__(*args, **kwargs)


class PetitionForm(forms.ModelForm):
    class Meta:
        model = PetitionForAdmin
        image = forms.ImageField(required=False, widget=FileInput,label='Elegir imagen')
        fields = [
            'title', 'message'
        ]
        labels = {
            'title': 'Título',
            'message': 'Descripción',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control mx-auto font32'}),
            'message': forms.Textarea(attrs={'class': 'storyMessageInput keepWhitespaceFormatting'}),
        }

    def __init__(self, *args, **kwargs):
        super(PetitionForm, self).__init__(*args, **kwargs)
        self.fields['message'].strip = False

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label='Contraseña')
    username = forms.CharField(label='Nombre de usuario',max_length=15)
    email = forms.CharField(widget=forms.EmailInput, label='Email')

    class Meta:
        model = User
        fields = [
            'username', 'email', 'password'
        ]
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        username = self.visible_fields()[0]
        email = self.visible_fields()[1]
        password = self.visible_fields()[2]
        username.field.widget.attrs['class'] = 'form-control createUserInput usernameInput'
        email.field.widget.attrs['class'] = 'form-control createUserInput emailInput'
        password.field.widget.attrs['class'] = 'form-control createUserInput passwordInput'


class UserProfileForm(forms.ModelForm):
    birthdate = forms.DateField(label='Fecha de nacimiento(Recuerda que si eres menor a 60 años no podrás escribir historias)',widget=forms.TextInput(attrs=
                                {
                                    'class':'datepicker'
                                }))
    biography = forms.CharField(widget=forms.Textarea, label='biografía(pequeña descripción sobre tu persona)-Opcional',
                                required=False)
    profileImage = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'file-field '}), label='Foto de perfil -Opcional')

    class Meta:
        model = UserWithProfile
        fields = [
            'birthdate', 'biography'
        ]

        labels = {
            'birthdate': 'Fecha de nacimiento',
            'biografía': 'Biografía(pequeña descripción sobre tu persona)'
        }

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        date = self.visible_fields()[0]
        bio = self.visible_fields()[1]
        date.field.widget.attrs['class'] = 'form-control createUserInput dateInput'
        bio.field.widget.attrs['class'] = 'form-control createUserInput bioInput'

class UserProfileFormUpdate(forms.ModelForm):
    birthdate = forms.DateField(label='Fecha de nacimiento(Recuerda que si eres menor a 55 años no podrás escribir historias)',widget=forms.TextInput(attrs=
                                {
                                    'class':'datepicker'
                                }))
    biography = forms.CharField(widget=forms.Textarea, label='biografía(pequeña descripción sobre tu persona)-Opcional',
                                required=False)

    class Meta:
        model = UserWithProfile
        fields = [
            'birthdate', 'biography'
        ]

        labels = {
            'birthdate': 'Fecha de nacimiento',
            'biografía': 'Biografía(pequeña descripción sobre tu persona)'
        }

    def __init__(self, *args, **kwargs):
        super(UserProfileFormUpdate, self).__init__(*args, **kwargs)
        date = self.visible_fields()[0]
        bio = self.visible_fields()[1]
        date.field.widget.attrs['class'] = 'form-control createUserInput dateInput'
        bio.field.widget.attrs['class'] = 'form-control createUserInput bioInput'


class UserLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label='Contraseña')
    username = forms.CharField(label='Nombre de usuario')
    class Meta:
        model = UserWithProfile
        fields = [
            'username', 'password'
        ]

class CommentForm(forms.ModelForm):
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'storyMessageInput keepWhitespaceFormatting'}), label='Comentario')
    class Meta:
        model = Comment
        fields = [
            'message'
        ]
        widgets = {
            'message': forms.Textarea(attrs={'class': 'storyMessageInput keepWhitespaceFormatting'}),
        }

WisApp/app/templates/app/categories.html
{% extends 'app/titleBar.html' %}
{% load staticfiles %}
{%load filters%}
{% block bodyContent %}

<div class="container-fluid mt-5">
    <div class="mb-5">
        <h1 class=" text-center w-100 " style="font-weight: bold">Categorías</h1>
    </div>

    {%for category in categories%}
    <div class="card mb-5">
        <div class="card-body"
             style="border: 0px solid {{category.color}}; background-color: {{category.color}}1; border-radius: 10px; font-weight: bolder;">
            <h1 class="card-title mt-2 categoryTitle text-center" style="color: {{category.color}};">
                {{category.name}}</h1>
            <a class="nounderline " href="#">
                <div class="storyText mt-2">
                    <p class="text-dark text-center "> {{category.description}}
                    </p>
                </div>
            </a>
            <div class=" categoryFooter text-center" style="border-top: 3px solid {{category.color}}">
                <a href="{%url 'app:filteredHome' category.id category.name%}"
                   class="btn btn-primary btn-sm text-light mt-2">
                    <h2>Ver historias</h2>
                </a>
                {%if userProfile|followed_category:category.id%}
                    <form method="post">
                        {%csrf_token%}
                        <input type="text" style="display: none;" value="unfollow" name="followCategory">
                        <input style="display: none" type="number" value="{{category.id}}" name="categoryId">
                        <button type="submit" class="btn btn-danger btn-sm text-light mt-2">
                            <h2>
                                Dejar de Seguir
                            </h2>
                        </button>
                    </form>
                    {%else%}
                         <form method="post">
                                {%csrf_token%}
                                <input type="text" style="display: none;" value="follow"name="followCategory">
                                <input style="display: none" type="number" value="{{category.id}}" name="categoryId">
                                <button type="submit" class="btn btn-success btn-sm text-light mt-2">
                                    <h2>
                                        Seguir Categoría
                                    </h2>
                                </button>
                            </form>
                    {%endif%}
            </div>
        </div>
    </div>
    {%endfor%}
</div>

{%endblock%}

WisApp/app/templates/app/home.html
{% extends 'app/titleBar.html' %}
{% load staticfiles %}
{%load filters%}
{% block bodyContent %}

<div style="border-bottom: 1px solid {{category.color}}"></div>
<div class="container-fluid mt-5">
     {%if not stories%}
            {%if favoriteStories%}
                <h1 class="bodyTitle text-center">Favoritas</h1>
                <div class="text-center">
                    <h1 class="text-primary"> Aún no tienes historias favoritas</h1>
                    <a class="nounderline" href="{%url 'app:profile' request.user.id%}"><div class=" mt-5 btn btn-lg btn-success text-light">Regresar</div></a>
                </div>
            {%elif category%}
                    {%if category.isEvent%}
                         <h1 class="bodyTitle text-center">{{category.name}}</h1>
                        <div class="text-center">
                            <h1 class="text-primary"> Aún no hay historias de {{category.name}}</h1>
                            <a class="nounderline" href="{%url 'app:events'%}"><div class=" mt-5 btn btn-lg btn-success text-light">Regresar</div></a>
                            <br>
                            <br>
                            <a class="nounderline" href="{%url 'app:createStory'%}"><div class=" btn btn-lg btn-primary text-light">Escribir historia</div></a>
                        </div>
                    {%else%}
                        <h1 class="bodyTitle text-center">{{category.name}}</h1>
                        <div class="text-center">
                            <h1 class="text-primary"> Aún no hay historias de {{category.name}}</h1>
                            <a class="nounderline" href="{%url 'app:categories'%}"><div class=" mt-5 btn btn-lg btn-success text-light">Regresar</div></a>
                            <br>
                            <br>
                            <a class="nounderline" href="{%url 'app:createStory'%}"><div class=" btn btn-lg btn-primary text-light">Escribir historia</div></a>
                        </div>
            {%endif%}
    {%else%}
            {%if category%}
                <h1 class="bodyTitle text-center">Historias de {{category.name}}</h1>
            {%else%}
                <h1 class="bodyTitle text-center">Historias</h1>
            {%endif%}
                <div class="text-center">
                    {%if extraData%}
                    <h1 class="text-primary w-100"> No se encontraron historias ni usuarios relacionados</h1>
                    <a class="nounderline" href="{%url 'app:home'%}"><div class=" mt-5 btn btn-lg btn-success text-light">Inicio</div></a>
                    {%else%}
                    <h1 class="text-primary"> Aún no escribes ninguna historia</h1>
                    <a class="nounderline" href="{%url 'app:createStory'%}"><div class=" mt-5 btn btn-lg btn-success text-light">Escribir historia</div></a>
                    {%endif%}
                </div>

            {%endif%}
    {%endif%}
    {% if messages %}
        <ul class="messages text-info text-left">
            {% for message in messages %}
                    {% if message.tags %} class="{{ message.tags }}" {% endif %}>*<h2>{{ message }}</h2>
            {% endfor %}
        </ul>
        {% endif %}
    <div class="card-deck">
        {%for story in stories%}
        <div class="card mb-5">
            <div class="card-body">
                {%if story.image%}
                <a class="nounderline" href="#"><img class="img-fluid" style="display: block; border: 1px solid rgba(50,50,50,0.1); margin: 0 auto;" src="{{story.image.url}}"></a>
                {%endif%}
                <div class="text-center">
                    <h1 class="card-title text-dark mt-2">{{story.title}}</h1>
                </div>
                <h4 class="card-subtitle text-dark my-3"><a class="nounderline text-dark" href="{%url 'app:profile' story.author.user.id%}">Escrita por <span
                        class="text-primary"> {{story.author}}</span></a></h4>
                <a href="{%url 'app:filteredHome' story.category.id story.category.name%}" class="btn btn-sm text-light"
                   style="background-color: {{story.category.color}} ;">
                    <h5>{{story.category}}</h5>
                </a>
                {%if userProfile == story.author%}
                <div style="border-top: 1px solid darkgray" class="mt-1">
                    <a class="nounderline" href="{%url 'app:storyUpdate' story.id%}"><div class="btn btn-sm btn-primary text-light">Editar</div></a>
                     <a class="nounderline" href="{%url 'app:storyDelete' story.id%}"><div class="btn btn-sm btn-danger text-light">Borrar</div></a>
                </div>
                {%endif%}
                <a class="nounderline " href="{%url 'app:story' story.pk %}">
                    <div class="storyText mt-2">
                        <p class="text-dark ">{{story.message}}
                        </p>
                    </div>
                </a>
                <div class="readMoreText">
                    <a href="{%url 'app:story' story.id %}" class="nounderline text-primary">Expandir Historia...</a>
                </div>
                <div class="card-footer bg-transparent mt-2 .d-md-none .d-lg-block">
                    <ul class="interactFooter">
                        <li>
                            <a class="nounderline text-dark" style="text-decoration: none;" href="{%url 'app:story' story.id%}">
                            <img class="img-fluid mt-3" src="{%static 'media/commentIcon.png' %}" width="48px"><span
                                class="interactIcons ">Comentarios</span>
                            </a>
                        </li>
                        <li>
                            {%if userProfile|favorited_Story:story.id%}
                                 <form method="post">
                                    {%csrf_token%}
                                    <input type="text" style="display: none;" value="unfavorite" name="favStory">
                                    <input style="display: none" type="number" value="{{story.id}}" name="storyId">
                                    <button type="submit">
                                        <img class="img-fluid mt-3 "
                                            src="{%static 'media/starFull.png' %}" width="48px"><span
                                            class="interactIcons text-primary">Es Favorita</span>
                                    </button>
                                </form>
                            {%else%}
                                <form method="post">
                                    {%csrf_token%}
                                    <input type="text" style="display: none;" value="favorite" name="favStory">
                                    <input style="display: none" type="number" value="{{story.id}}" name="storyId">
                                    <button type="submit">
                                        <img class="img-fluid mt-3 "
                                            src="{%static 'media/starEmpty.png' %}" width="48px"><span
                                            class="interactIcons">Hacer Favorita</span>
                                    </button>
                                </form>
                            {%endif%}
                        </li>
                        <li>

                            {%if userProfile|liked_Story:story.id%}
                                 <form method="post">
                                    {%csrf_token%}
                                    <input type="text" style="display: none;" value="unlike" name="likeStory">
                                    <input style="display: none" type="number" value="{{story.id}}" name="storyId">
                                    <button type="submit" class="text-primary">
                                        <img class="img-fluid  mt-3 "
                                 src="{%static 'media/likeIcon.png' %}" width="48px"><span
                                class="interactIcons">{{story.ranking}} Me gusta</span>
                                    </button>
                                </form>
                            {%else%}
                                <form method="post">
                                    {%csrf_token%}
                                    <input type="text" style="display: none;" value="like" name="likeStory">
                                    <input style="display: none" type="number" value="{{story.id}}" name="storyId">
                                    <button type="submit" class="">
                                         <img class="img-fluid  mt-3 "
                                 src="{%static 'media/likeIcon.png' %}" width="48px"><span
                                class="interactIcons">{{story.ranking}} Me gusta</span>
                                    </button>
                                </form>
                            {%endif%}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
</div>
{%endblock%}

WisApp/app/templates/app/titleBar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Wisapp</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="{%static 'app/autosize/src/autosize.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{%static 'app/styles.css' %}"/>
</head>
<body>
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light static-top">
    <a class="navbar-brand" href="{%url 'app:home'%}">Wisapp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <form class="form-inline my-2 my-lg-0" method="get" action="{%url 'app:home'%}">
        <input class="form-control mr-sm-2" type="search" placeholder="..." aria-label="Search" name="q">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'app:home'%}"><img class="d-sm-block d-md-none"
                                                                   src="{%static 'media/homeIcon.png' %}"
                                                                   width="48px">Inicio <span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'app:categories'%}"><img class="d-sm-block d-md-none"
                                                                         src="{%static 'media/categoryIcon.png' %}"
                                                                         width="48px">Categorías</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{%url 'app:events'%}"><img class="d-sm-block d-md-none"
                                                                      src="{%static 'media/eventIcon.png' %}"
                                                                      width="48px">Eventos</a>
            </li>
            <li class="nav-item">
                {%if userProfile.isAdult%}
                <a class="nav-link " href="{%url 'app:createStory'%}"><img class="d-sm-block d-md-none"
                                                                           src="{%static 'media/writeStory.png' %}" width="48px">Escribir</a>
                {%endif%}
            </li>
        </ul>
        <ul>
            <li>
                <div class="dropdown btn btn-sm usernameTitleButton" style="border: 2px solid rgba(50,50,50,0.1); border-radius: 10px">
                    <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        {{request.user.username}}
                    </div>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{%url 'app:profile' request.user.id%}"><h3>Ver perfil</h3></a>
                        <a class="dropdown-item" href="{%url 'app:logout'%}"><h3>Salir</h3></a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</nav>
</div>

<input type="hidden" id="refreshed" value="false">
<script type="text/javascript">
    $(window).on('load', function() {
        if ($('#refreshed').val() == "false") {
          $('#refreshed').val("true");
        }
        else {
          $('#refreshed').val("false");
          location.reload();
        }
      });
</script>
{%block bodyContent%}

{% endblock%}
</body>

</html>

WisApp/app/templates/app/viewProfile.html
{% extends 'app/titleBar.html' %}
{% load staticfiles %}
{% block bodyContent %}
{%if userProfile.user.id == request.user.id%}
<!-- PERSONAL PROFILE -->
    <div class="container-fluid mt-5">
        <div class="card mb-2">
            <div class="card-body">
                {%if userProfile.profileImage%}
                    <a class="nounderline" href="{%url 'app:UserWithProfileUpdate' userProfile.id%}"><img class="img-fluid" src="{{userProfile.profileImage.url}}"
                                                     style="max-height: 400px; display: block; margin: 0 auto"></a>
                {%else%}
                    <div class="text-center">
                        <a href="{%url 'app:UserWithProfileUpdate' userProfile.id%}" class=" text-light nounderline btn btn-primary">Subir foto de perfil</a>
                    </div>
                {%endif%}
                <h1 class="card-title text-dark text-center mt-2"><a href="{%url 'app:profile' request.user.id%}" class="nounderline text-dark" style="font-weight: bolder;"> {{userProfile.user.username}}</a></h1>
                <h2 class="text-center"><br></h2>
                <a class="nounderline " href="">
                    <div class="storyTextFull mt-1">
                        <p class="text-dark w-75 text-center mx-auto" style="font-size: 30px">{{userProfile.biography}}
                        </p>
                    </div>
                </a>
            </div>
        </div>

        <div class="card mb-2">
            <div class="card-body text-center">
                <ul class="ml-0 pl-0">
                    {%if request.user.is_superuser%}
                    <li class="my-4" style="border-bottom:  1px solid rgba(50,50,50,0.5);"><a href="{%url 'app:showStatistics'%}" class="text-success nounderline">Ver Estadísticas</a> </li>
                    {%endif%}
                    {%if isAdult%}
                    <li class="my-4" style="border-bottom:  1px solid rgba(50,50,50,0.5);"><a href="{%url 'app:homeMyStories'%}" class="text-primary nounderline">Mis historias</a> </li>
                    {%endif%}
                    <li class="my-4" style="border-bottom:  1px solid rgba(50,50,50,0.5);"><a href="{%url 'app:homeMyFavoriteStories'%}" class="text-primary nounderline">Mis historias favoritas</a> </li>

                    <li class="my-4" style="border-bottom:  1px solid rgba(50,50,50,0.5);"><a href="{%url 'app:followedAuthors'%}" class="text-primary nounderline">Autores que sigo</a> </li>
                    <li class="my-4" style="border-bottom:  1px solid rgba(50,50,50,0.5);"><a href="{%url 'app:UserWithProfileUpdate' userProfile.id%}" class="text-primary nounderline">Editar información de perfil</a> </li>
                    <li class="my-4" style="border-bottom:  1px solid rgba(50,50,50,0.5);"><a href="{%url 'app:createPetition'%}" class="text-primary nounderline">Escribir una sugerencia  o queja</a> </li>
                    <li class="my-4" style="border-bottom:  1px solid rgba(50,50,50,0.5);"><a href="{%url 'app:userwithprofileDelete' request.user.id%}" class="text-danger nounderline">Borrar Cuenta</a> </li>
                </ul>
            </div>
        </div>
    </div>
{%else%}
<!-- FRIEND PROFILE -->
    <div class="container-fluid mt-5">
        <div class="card mb-2">
            <div class="card-body">
                {%if userProfile.profileImage%}
                    <a class="nounderline"><img class="img-fluid" src="{{userProfile.profileImage.url}}"
                                                     style="max-height: 400px; display: block; margin: 0 auto"></a>
                {%endif%}
                <h1 class="card-title text-dark text-center mt-2"><a class="nounderline text-dark" style="font-weight: bolder;"> {{userProfile.user.username}}</a></h1>
                <h2 class="text-center"><br></h2>
                <a class="nounderline " >
                    <div class="storyTextFull mt-1">
                        <p class="text-dark w-75 text-center mx-auto" style="font-size: 30px">{{userProfile.biography}}
                        </p>
                    </div>
                </a>
            </div>
        </div>
        <div class="card mb-2">
            <div class="card-body text-center">
                <ul class="ml-0 pl-0">
                    <li class="my-4" style="border-bottom:  1px solid rgba(50,50,50,0.5);"><a href="{%url 'app:storyFilterByAuthor' userProfile.id%}" class="text-primary nounderline"> Ver sus historias</a> </li>
                        {%if userIsFollowed%}
                            <form method="post">
                                    {%csrf_token%}
                                    <input type="text" style="display: none;" value="unfollow"name="followUserProfile">
                                    <input style="display: none" type="number" value="{{userProfile.id}}" name="userProfileId">
                                    <button type="submit" class="btn btn-danger btn-sm text-light mt-2">
                                        <h2>
                                            dejar de seguir
                                        </h2>
                                    </button>
                            </form>
                        {%else%}
                            <form method="post">
                                    {%csrf_token%}
                                    <input type="text" style="display: none;" value="follow"name="followUserProfile">
                                    <input style="display: none" type="number" value="{{userProfile.id}}" name="userProfileId">
                                    <button type="submit" class="btn btn-success btn-sm text-light mt-2">
                                        <h2>
                                            Seguir
                                        </h2>
                                    </button>
                            </form>
                        {%endif%}
            </div>
        </div>
    </div>
{%endif%}
{%endblock%}